version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: licenta_db
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: reading
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d reading"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - dbdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:8
    container_name: licenta_pgadmin
    ports: ["5050:80"]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on: [db]
volumes:
  dbdata: {}
  pgadmindata: {}
